import React from "react";
import {StyleSheet} from "react-native"
const Style=StyleSheet.create({
    //home
    header:{
        flexDirection:"row",
        height:50,
        borderColor:"#e3e3e3",
        borderBottomWidth:2,
        borderTopWidth:2,
    },
    flex_row:{
        flexDirection:"row",
        paddingLeft:2,
        paddingRight:2,
        marginLeft:10,
        paddingTop:1,
        borderColor:"#e3e3e3",
        borderBottomWidth:2,
    },
    movie_image:{
       flex:1,
        paddingTop:10,
        paddingBottom:10
    },
    image:{
        width:100,
        height:150,
    },
    movie_item:{
        flex:2.5,
        marginTop:15,
    },
    movie_item_title:{
      flexDirection:"row",
        alignItems:"center"
    },
    movie_item_3D:{
        width:30,
        backgroundColor:"#96CDCD",
        textAlign:"center",
        color:"#fff",
        borderWidth:2,
        borderColor:"#96CDCD"
    },
    movie_item_IMAX:{
        width:40,
        textAlign:"center",
        borderWidth:2,
        borderColor:"#96CDCD"
    },
    movie_buy:{
        flex:0.8,
        alignItems:"center",
        justifyContent:"center"
    },
    //details
    movie_details_image:{
        width:120,
        height:100,
    },
    movie_details_title:{
        marginLeft:20,
    },
});
module.exports=Style;